defaults:
  - core_dm_mixing_base
  - transform@patch_transform_train: no_augs
  - transform@patch_transform_eval: no_augs
  - splits: all_centers
  - _self_

loader_config:
  batch_size: 1
  num_workers: 8
  balance_classes_train: False

patch_view_config: 
  prostate_region_only: False 
  needle_region_only: True
  
splits: 
  merge_val_centers: yes 
  merge_test_centers: yes

mixing_options: 
  fold_increase: 3