
# TODO this is not tested

defaults:
  - patch_datamodule_base
  - transform@patch_transform_train: default
  - transform@patch_transform_eval: no_augs
  - splits: uva600
  - _self_ 

_target_: src.lightning.datamodules.exact_datamodule.PatchDataModuleForSemiSupervisedLearningFahimeh

patch_view_config: 
  needle_region_only: false
  prostate_region_only: true

splits: 
  cohort_specifier: [UVA600, CRCEO428]
  undersample_benign_eval: true
  undersample_benign_train: true
  