# TODO this is not tested

defaults:
  - patch_datamodule_base
  - transform@patch_transform_train: default
  - transform@patch_transform_eval: no_augs
  - splits: uva_crceo
  - _self_ 

_target_: src.lightning.datamodules.exact_datamodule.PatchDataModuleForSelfSupervisedLearning

loader_config:
  batch_size: 128

patch_view_config: 
  needle_region_only: false
  prostate_region_only: true

splits: 
  undersample_benign_eval: true
  undersample_benign_train: true
  