defaults:
  - patch_datamodule_base
  - transform@patch_transform_train: no_augs
  - transform@patch_transform_eval: no_augs
  - splits: all_centers
  - _self_

_target_: src.lightning.datamodules.exact_datamodule.PatchDataModuleForSupervisedLearning

loader_config:
  batch_size: 32

patch_view_config: 
  needle_region_only: true 
  prostate_region_only: false


splits: 
  undersample_benign_eval: true
